## Exo 1 
Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [2]:
import numpy as np

x= []
for i in range(11):
    x.append(i)

x = np.array(x)

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Exo 2
Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [3]:
rand = np.random.default_rng()
y= rand.random(5)
print(y)

[0.37632104 0.5307815  0.93180902 0.58295534 0.85089872]


## Exo 3 
Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [4]:
#basique
def somme(tab:np.array):
    res = 0
    for i in tab: 
        res = res + i
    print(res)

somme(y)

3.2727656296933008


In [5]:
#numpy specific
print(np.sum(y))

3.2727656296933008


## Exo 4 
Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [6]:

a = rand.random(3)
b= rand.random(3)
print(np.dot(a,b))

0.5087184078976126


## Exo 5 
Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [7]:
c = np.array([1,1,1,2,3,4,5])
c_unique = np.unique(c)
print(c_unique)

[1 2 3 4 5]


## Exo 6
Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [8]:
d = rand.random(10)
print('gen: ',d)
d = np.sort(d)
print('sorted :',d)

gen:  [0.14532139 0.02774874 0.51395772 0.50224315 0.30061947 0.93923615
 0.87366007 0.48081177 0.22038989 0.87963821]
sorted : [0.02774874 0.14532139 0.22038989 0.30061947 0.48081177 0.50224315
 0.51395772 0.87366007 0.87963821 0.93923615]


## Exo 7
Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [9]:
e = rand.random(10)
moy = np.mean(e)
med = np.median(e)
sigma = np.std(e)
print(f' {e=} \n {moy=} \n {med=} \n {sigma=}')

 e=array([0.99812282, 0.88225133, 0.12378494, 0.69327865, 0.36164271,
       0.69278967, 0.15064859, 0.51527681, 0.90868802, 0.1694277 ]) 
 moy=0.549591125437201 
 med=0.6040332422170402 
 sigma=0.31677095344950584


## Exo 8
Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [15]:
z= np.arange(10)
print(z)
np.place(z,z<5,[0])
np.place(z,z>=5,[1])
print(z)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 1 1 1 1 1]


## Exo 9
Créez un tableau NumPy 2D de taille 3x3 contenant des valeurs entières générées aléatoirement entre 1 et 10.

In [22]:
rng = np.random.default_rng()
arr = rng.integers(low=1, high=10,size=9)
print(arr)
arr_2d = np.reshape(arr,(3,3))
print(arr_2d)

[7 9 2 5 6 2 1 1 5]
[[7 9 2]
 [5 6 2]
 [1 1 5]]
