## Exo 1 
Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [11]:
import numpy as np

x= []
for i in range(11):
    x.append(i)

x = np.array(x)

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Exo 2
Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [12]:
rand = np.random.default_rng()
y= rand.random(5)
print(y)

[0.35465836 0.65038866 0.57802157 0.72771414 0.56261376]


## Exo 3 
Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [13]:
#basique
def somme(tab:np.array):
    res = 0
    for i in tab: 
        res = res + i
    print(res)

somme(y)

2.873396487331898


In [14]:
#numpy specific
print(np.sum(y))

2.873396487331898


## Exo 4 
Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [16]:

a = rand.random(3)
b= rand.random(3)
print(np.dot(a,b))

0.21124952213458462


## Exo 5 
Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [18]:
c = np.array([1,1,1,2,3,4,5])
c_unique = np.unique(c)
print(c_unique)

[1 2 3 4 5]


## Exo 6
Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.