## Exo 1 
Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [1]:
import numpy as np

x= []
for i in range(11):
    x.append(i)

x = np.array(x)

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Exo 2
Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [2]:
rand = np.random.default_rng()
y= rand.random(5)
print(y)

[0.87443058 0.08138092 0.88989607 0.61964538 0.70466354]


## Exo 3 
Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [3]:
#basique
def somme(tab:np.array):
    res = 0
    for i in tab: 
        res = res + i
    print(res)

somme(y)

3.1700164967112796


In [4]:
#numpy specific
print(np.sum(y))

3.1700164967112796


## Exo 4 
Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [5]:

a = rand.random(3)
b= rand.random(3)
print(np.dot(a,b))

1.0380989220944317


## Exo 5 
Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [6]:
c = np.array([1,1,1,2,3,4,5])
c_unique = np.unique(c)
print(c_unique)

[1 2 3 4 5]


## Exo 6
Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [7]:
d = rand.random(10)
print('gen: ',d)
d = np.sort(d)
print('sorted :',d)

gen:  [0.43084922 0.44928049 0.60025952 0.89932066 0.1847155  0.33068967
 0.10543396 0.52078273 0.73895968 0.57747484]
sorted : [0.10543396 0.1847155  0.33068967 0.43084922 0.44928049 0.52078273
 0.57747484 0.60025952 0.73895968 0.89932066]


## Exo 7
Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [8]:
e = rand.random(10)
moy = np.mean(e)
med = np.median(e)
sigma = np.std(e)
print(f' {e=} \n {moy=} \n {med=} \n {sigma=}')

 e=array([0.3151823 , 0.39656023, 0.7268321 , 0.88251209, 0.78818334,
       0.87266147, 0.38039709, 0.22551645, 0.1865668 , 0.71793165]) 
 moy=0.5492343523874015 
 med=0.5572459385548221 
 sigma=0.2599408231313398


## Exo 8
Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [9]:
z= np.arange(10)
print(z)
np.place(z,z<5,[0])
np.place(z,z>=5,[1])
print(z)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 1 1 1 1 1]


## Exo 9
Créez un tableau NumPy 2D de taille 3x3 contenant des valeurs entières générées aléatoirement entre 1 et 10.

In [10]:
rng = np.random.default_rng()
arr = rng.integers(low=1, high=10,size=9)
print(arr)
arr_2d = np.reshape(arr,(3,3))
print(arr_2d)

[4 5 9 2 2 4 7 1 9]
[[4 5 9]
 [2 2 4]
 [7 1 9]]
