## Random
Test np.random et random seul  

In [45]:
import numpy as np
import random

# np : créer un générateur, à appeler au besoin
rng = np.random.default_rng()
print(rng)


a = rng.random(size=20)
print(type(a))
a


Generator(PCG64)
<class 'numpy.ndarray'>


array([0.96677685, 0.72566961, 0.95598105, 0.96450527, 0.14934901,
       0.93954244, 0.41051887, 0.2119009 , 0.0303837 , 0.41492512,
       0.97441848, 0.98339026, 0.1447932 , 0.16817103, 0.9493345 ,
       0.19474144, 0.648785  , 0.46190568, 0.57451777, 0.71581447])

In [46]:
my_list = [1, 2 , 3, 4, 5, 6]
print(type(my_list))
print(id(my_list))

<class 'list'>
2018726040064


In [47]:
b = np.array(my_list)
print(type(b[0]))
print(b)
print(type(my_list))
print(id(b))


<class 'numpy.int32'>
[1 2 3 4 5 6]
<class 'list'>
2018735398640


In [48]:
c = np.asarray(my_list)
print(type(c[0]))
c
print(type(my_list[0]))
print(id(c))



<class 'numpy.int32'>
<class 'int'>
2018735801616


In [49]:
c[0]=5
b[0]=5
print(my_list)
print(c)
print(b)

[1, 2, 3, 4, 5, 6]
[5 2 3 4 5 6]
[5 2 3 4 5 6]
